baseURL = "https://integratedturtle.github.io/BRG4-IO/"
languageCode = "de-de"
title = "BG und BRG4-IOI"
theme = "ink"
paginate = 5

copyright = "Sir Karl Popper Schule"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

[params]
	subtitle = "Alle infos zum Informatik-Olympiade Club des BG und BRG4"

	# Optional 64x64 avatar image.
	avatar = ""

	# Content types to disable Disqus on.  disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.
enableNestedContent = true

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Updates"
url = "/updates"
weight = 2

[[menu.main]]
name = "Tutorial"
url = "/tutorial"
weight = 3

[[menu.main]]
name = "Aufgaben"
url = "/aufgaben"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/IntegratedTurtle/BRG4-IO/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
