baseURL = "http://example.org/"
languageCode = "de-de"
title = "BRG4-IOI"
theme = "ink"
paginate = 5

copyright = "Sir Karl Popper Schule"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "Alle infos zum Informatik-Olympiade Club des BRG4"

	# Optional 64x64 avatar image.
	avatar = ""

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Updates"
url = "/updates"
weight = 2

[[menu.main]]
name = "Tutorials"
url = "/tutorials"
weight = 3

[[menu.main]]
name = "Aufgaben"
url = "/aufgaben"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/knadh/hugo-ink"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
